# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MacroChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MacroChallenge
	pod 'Alamofire', '~> 5.2'

  target 'MacroChallengeTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Nimble-Snapshots'
  	pod 'Quick'
  end

  target 'MacroChallengeUITests' do
    # Pods for testing
  end

end
